import deleteIcon from "../../assets/images/optionsButtonIcons/deleteIcon.png";
import detailsIcon from "../../assets/images/optionsButtonIcons/detailsIcon.png";
import quoteIcon from "../../assets/images/optionsButtonIcons/charm_circle-tick.svg";

export const availableOptions = [
  {
    title: "Quote",
    icon: quoteIcon,
    to: "/account/inbounds/prescriptions/create-quote",
  },
  {
    title: "View Details",
    icon: detailsIcon,
    to: "/account/inbounds/prescriptions/prescription-details",
  },
];

export const acceptedPendingOptions = [
  {
    title: "Dispense Order",
    icon: quoteIcon,
    to: "/account/inbounds/create-receipt",
  },
  {
    title: "Delete Order",
    icon: deleteIcon,
    onClick: () => {
      // Add your delete logic here
    },
  },
  {
    title: "View Details",
    icon: detailsIcon,
    to: "account/inbounds/prescriptions",
  },
];

export const accepteddispensedOptions = [
  {
    title: "Delete Order",
    icon: deleteIcon,
    onClick: () => {
      // Add your delete logic here
    },
  },
  {
    title: "View Details",
    icon: detailsIcon,
    to: "account/inbounds/prescriptions",
  },
];

export const data = [
  {
    id: "#5094834932",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "Sunday Peters",
    dispensedStatus: "pending",
    quotedStatus: "Pending",
    amount: 5000,
    accepted: true,
  },
  {
    id: "#50394872562",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "James Oshiomole",
    dispensedStatus: "pending",
    quotedStatus: "quoted",
    amount: 5000,
    accepted: true,
  },
  {
    id: "#5094245284",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "Okinda Peters",
    dispensedStatus: "pending",
    quotedStatus: "Quoted",
    amount: 5000,
    accepted: false,
  },
  {
    id: "#503948424",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "Sunday Peters",
    dispensedStatus: "pending",
    quotedStatus: "Pending",
    amount: 5000,
    accepted: false,
  },
  {
    id: "#509438373",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "Sunday Peters",
    dispensedStatus: "pending",
    quotedStatus: "Quoted",
    amount: 5000,
    accepted: true,
  },
  {
    id: "#5305948835",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "Sunday Peters",
    dispensedStatus: "pending",
    quotedStatus: "Pending",
    amount: 5000,
    accepted: false,
  },
  {
    id: "#5094823467",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "Sunday Peters",
    dispensedStatus: "pending",
    quotedStatus: "Pending",
    amount: 5000,
    accepted: false,
  },
  {
    id: "#540849448",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "Sunday Peters",
    dispensedStatus: "dispensed",
    quotedStatus: "quoted",
    amount: 5000,
    accepted: true,
  },
  {
    id: "#5098456484",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "Sunday Peters",
    dispensedStatus: "pending",
    quotedStatus: "Pending",
    amount: 5000,
    accepted: false,
  },
  {
    id: "#5094849453",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "Sunday Peters",
    dispensedStatus: "pending",
    quotedStatus: "Quoted",
    amount: 5000,
    accepted: false,
  },
  {
    id: "#509484935",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "Sunday Peters",
    dispensedStatus: "dispensed",
    quotedStatus: "quoted",
    amount: 5000,
    accepted: true,
  },
  {
    id: "#505948847",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "Sunday Peters",
    dispensedStatus: "pending",
    quotedStatus: "quoted",
    amount: 5000,
    accepted: true,
  },
  {
    id: "#509488354",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "Sunday Peters",
    dispensedStatus: "pending",
    quotedStatus: "Quoted",
    amount: 5000,
    accepted: true,
  },
  {
    id: "#50948426",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "Sunday Peters",
    dispensedStatus: "pending",
    quotedStatus: "Pending",
    amount: 5000,
    accepted: false,
  },
  {
    id: "#50948834",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "Sunday Peters",
    dispensedStatus: "pending",
    quotedStatus: "Quoted",
    amount: 5000,
    accepted: false,
  },
  {
    id: "#509484863",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "Sunday Peters",
    dispensedStatus: "dispensed",
    quotedStatus: "Quoted",
    amount: 5000,
    accepted: true,
  },
  {
    id: "#50948440435",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "Sunday Peters",
    dispensedStatus: "pending",
    quotedStatus: "Pending",
    amount: 5000,
    accepted: false,
  },
  {
    id: "#5049484238",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "Sunday Peters",
    dispensedStatus: "dispensed",
    quotedStatus: "Quoted",
    amount: 5000,
    accepted: true,
  },
  {
    id: "#5094840656",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "Sunday Peters",
    dispensedStatus: "pending",
    quotedStatus: "Quoted",
    amount: 5000,
    accepted: false,
  },
  {
    id: "#5094834953",
    date: "12 April 2023, 12:43 AM",
    uploadName: "Prescription.png",
    pharmacyName: "Sunday Peters",
    dispensedStatus: "pending",
    quotedStatus: "Pending",
    amount: 5000,
    accepted: true,
  },
];
