// list of transactions and their details
export const listOfPrescriptions = [
    {
        id: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "Sunday Peters",
        location: "No 4, Ike road, Amaku",
        filterOption: "Pending",
    },
    {
        id: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "James Oshiomole",
        location: "No 4, Ike road, Amaku",
        filterOption: "Dispensed",
    },
    {
        id: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "Okinda Peters",
        location: "No 4, Ike road, Amaku",
        filterOption: "Quoted",
    },
    {
        id: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "Sunday Peters",
        location: "No 4, Ike road, Amaku",
        filterOption: "Pending",
    },
    {
        id: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "Sunday Peters",
        location: "No 4, Ike road, Amaku",
        filterOption: "Quoted",
    },
    {
        id: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "Sunday Peters",
        location: "No 4, Ike road, Amaku",
        filterOption: "Pending",
    },
    {
        id: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "Sunday Peters",
        location: "No 4, Ike road, Amaku",
        filterOption: "Pending",
    },
    {
        id: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "Sunday Peters",
        location: "No 4, Ike road, Amaku",
        filterOption: "Dispensed",
    },
    {
        id: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "Sunday Peters",
        location: "No 4, Ike road, Amaku",
        filterOption: "Pending",
    },
    {
        id: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "Sunday Peters",
        location: "No 4, Ike road, Amaku",
        filterOption: "Quoted",
    },
    {
        id: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "Sunday Peters",
        location: "No 4, Ike road, Amaku",
        filterOption: "Dispensed",
    },
    {
        id: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "Sunday Peters",
        location: "No 4, Ike road, Amaku",
        filterOption: "Dispensed",
    },
    {
        orderID: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "Sunday Peters",
        location: "No 4, Ike road, Amaku",
        filterOption: "Quoted",
    },
    {
        orderID: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "Sunday Peters",
        location: "No 4, Ike road, Amaku",
        filterOption: "Pending",
    },
    {
        orderID: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "Sunday Peters",
        location: "No 4, Ike road, Amaku",
        filterOption: "Quoted",
    },
    {
        orderID: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "Sunday Peters",
        location: "No 4, Ike road, Amaku",
        filterOption: "Dispensed",
    },
    {
        orderID: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "Sunday Peters",
        location: "No 4, Ike road, Amaku",
        filterOption: "Pending",
    },
    {
        orderID: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "Sunday Peters",
        location: "No 4, Ike road, Amaku",
        filterOption: "Dispensed",
    },
    {
        orderID: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "Sunday Peters",
        location: "No 4, Ike road, Amaku",
        filterOption: "Quoted",
    },
    {
        orderID: "#509484939",
        date: "12 April 2023, 12:43 AM",
        clientName: "Sunday Peters",
        location: "No 4, Ike road, Amaku",
        filterOption: "Pending",
    },
]


export const filterOptions = ["Available prescriptions", "Quoted prescriptions", "Accepted quotes"];
export const filterParameters = [{name: "Pending", options: ["Quote", "View Details"]}, {name: "Quoted", options: ["Delete", "View Details"]}, {name: "Dispensed", options: ["Delete", "View Details"]}]
export const tableHeading = ["Prescription ID", "Date", "Client Name", "Location", "Status"]
